#ifndef SCHOLA_TRAINING_BINDINGS_REGISTER_TYPES_H
#define SCHOLA_TRAINING_BINDINGS_REGISTER_TYPES_H

void register_schola_training_binding_types();
void unregister_schola_training_binding_types();

#endif // SCHOLA_TRAINING_BINDINGS_REGISTER_TYPES_H
